# Initialize Alembic
alembic init alembic

# Edit alembic.ini
# sqlalchemy.url = postgresql://username:password@ep-xxx-xxx.us-east-1.aws.neon.tech/neondb?sslmode=require

# Create initial migration
alembic revision --autogenerate -m "Initial ticket system tables"

# Apply migration
alembic upgrade head